KeyError in line 24 of /data1/yztxwd/Github/chip-seq-standard-pipeline/Snakefile:
'replicate'
  File "/data1/yztxwd/Github/chip-seq-standard-pipeline/Snakefile", line 24, in <module>
  File "/data1/yztxwd/miniconda3/envs/common/lib/python3.7/site-packages/pandas/core/frame.py", line 2980, in __getitem__
  File "/data1/yztxwd/miniconda3/envs/common/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2899, in get_loc
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
